import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import MainMenu from "@/components/home/main-menu";
// import MainLayout from "@/components/home/main-layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <MainMenu /> */}
        {/* <MainLayout>{children}</MainLayout> */}
        {children}
      </body>
    </html>
  );
}
